---
- name: Install Clickhouse
  hosts: clickhouse
  gather_facts: true
  tags: "clickhouse"
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  gather_facts: true
  tags: "vector"
  roles:
    - vector

- name: Install Lighthouse
  become: true
  hosts: lighthouse
  gather_facts: true
  tags: "lighthouse"
  roles:
    - lighthouse

  pre_tasks:

    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Copy custom nginx.conf
      ansible.builtin.template:
        src: ./template/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

    - name: Set up nginx config directory
      ansible.builtin.file:
        path: /etc/nginx/{{ item }}
        state: directory
      with_items:
        - sites-available
        - sites-enabled

    - name: Copy nginx lighthouse.conf
      ansible.builtin.template:
        src: ./template/lighthouse.conf.j2
        dest: /etc/nginx/sites-available/{{ domain }}
        owner: '{{ nginx_user }}'
        group: '{{ nginx_user }}'
        mode: 0644
      notify: Restart nginx

    - name: Activate the lighthouse nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ domain }}
        state: link

    - name: Install git
      ansible.builtin.yum:
        name: git
        state: present

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
